language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "SIKuE34GATet4ORuxQqpoQJtbg/Xk/1nAQfrCrbBBYqgSfIKc/TEN5MSz+m0qqRp/b1Gr5xO2p7ziYTYYjXVRWzEkHtYH1k6JzwWEX16K1PBpDYLf2AbCWJqZINVmjeyJdq8aYCLA+5hcyqhufnJGCM/dZFuU/JigLFg7SQtF9SAfgNlGHW7rww4Mllw2/uY+7p9FzSoIux93vtVbKDPolqbkx1xYmGMJjgjt322Zd+1ZJyoBVavvDk1YrJODVe6BzU1NcyU/QJK+SQfYP3EVDMbABMyMDj+S9uNqj2rxtkcL3NzsRRsPKzBMIHjjqGM0whGAGxYpfTMs7Ymih+OK3sooNmLpuAxxxkUFK/D2CFuBUo5tWjOX/ngFzk769x0L9iMEwsTs2li00yFLH/JbhDf873zyZOdosTUyuEEfFjlUXptUYVwcmHPeYQAOcmNLQaiVXdTD37yCpddzMrC3dzxCs66NPq0D2xKQzuCjWlYgg+4R2gsLm1lDREW78b6BI2+sJo5Gk76hZK4UoVjvDeatTVuytxRjjMlrdGUOw4FPgKVvaOgtM0+XIfwvxIE7sB9OakUyQEKTvui0bs2vNTducco09LlXJ+WkAq89YnY8f67+vZiK6pBUiMYrTV3f3sGQ4dQ8OLd829UqYYIjUSQd4CWcBkLqp9wHt9LrY4="