language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: "fgyOCpOgkzV0sJed3pzmP0GjPj8wBlLju3tip9rgib2hAXJ98+r3YLzoeGwoySdNHSWmeznoeHSNhnTSdwr0uJcwhw8aRqdQ8B1SH9S0jfa2EF8meNSUJLKQXHlmlso+8+jP2MODcGNMJ1mrchjDUMoG7cnd75fmrLhDHbhrbTXhUhRFugEQ2Y9ht+KgUZOn/qgNCD8Huz35js0IdPt0tWz4/yEUa45I4seWaEYcgrTUbnEAb2IqlDy5g87GirJdGvNcLxlic/t4Y/pU2bHEvpW9cswMJryz9Do/6+u/KaisTXsn9MqBV3E1UjFx4KF6OxVkqlTzKcBj6loNMXrSRJQFxznH676POHZY47ZPGF4T7ekoyr0OcM8KgksPxHKojkWEgSj2ZkcUIqon/2Nde6R8O2RS/dGaJaExZD/52Rk7PCDrWYzZ+kBhll4zNql17tJ2nuWWXKa0TzBi0vQCsShtFHzUH9DsrK1s7ao6t99KAvlNQLpnY56hIMNrxFEZS2anbD64A0FLD+P3U3kb5hAmppEDi7SXrMXthWEh74CEOziZnBMkv7qNt7evxuU8xxd76r8jFfdpKNLKeB1lNeWA6AAwRbAxfx9im40q3LRXAI+VniwtfjFqKP7gk5pNhSHwMbxTnUXlg7CknuxscIV8L++cKtGWe5SLBHDXp+U="